name: infracost with slack

on:
  push:
    branches:
      - main
    paths:  
      - terraform/**

  pull_request:
    branches:
      - main
    paths:
      - terraform/**

  workflow_dispatch:

env:
  # Credentials for deployment to AWS
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  # S3 bucket for the Terraform state
  BUCKET_TF_STATE: ${{ secrets.BUCKET_TF_STATE }}
  AWS_REGION: us-west-2

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform plan and output to JSON
        id: plan
        run: |
          terraform plan -no-color -input=false -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json

      - name: Save Terraform plan
        uses: actions/upload-artifact@v3
        with:
          name: tfplan-json
          path: terraform/tfplan.json

  infracost-notification:
    name: "Infracost and Slack Notification"
    needs: terraform-plan
    runs-on: ubuntu-latest

    steps:
      - name: Download Terraform plan
        uses: actions/download-artifact@v3
        with:
          name: tfplan-json
          path: terraform/tfplan.json

      - name: Install Infracost
        run: curl -sSfL https://raw.githubusercontent.com/infracost/infracost/master/scripts/install.sh | sh

      - name: Setup Infracost API key
        run: infracost configure set api_key ${{ secrets.INFRACOST_API_KEY }}

      - name: Run Infracost breakdown
        run: infracost breakdown --path terraform/tfplan.json --format json --out-file infracost-out.json

      - name: Extract Cost Estimate
        id: extract_cost
        run: |
          TOTAL_COST=$(cat infracost-out.json | jq -r '.projects[0].diff.totalMonthlyCost')
          echo "TOTAL_COST=$TOTAL_COST" >> $GITHUB_ENV

      - name: Post Infracost result to PR
        uses: infracost/actions/comment@v1
        with:
          path: infracost-out.json

      - name: Notify Slack about cost estimation
        if: success() # This triggers the action only if the previous steps are successful.
        uses: wearerequired/slack-messaging-action@v2
        with:
          bot_token: ${{ secrets.SLACK_BOT_TOKEN }} # The Slack bot token stored in GitHub Secrets
          channel: infrastructure-budgets # Your Slack channel ID (use the actual channel ID without quotes)
          payload: >-
            {
              "icon_emoji": ":rocket:",
              "text": "Terraform plan and cost estimate complete! Check the cost estimate: ${{ env.TOTAL_COST }} per month"
            }
