name: cicd-workflow with slack integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  send-slack-notification:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
    - name: Send Slack notification with job status
      uses: act10ns/slack@v2
      with:
        channel: '#infrastructure-budgets'
        status: ${{ job.status }}  # This adds the job status (success, failure, etc.)
        steps: ${{ toJson(steps) }}
        text: 'GitHub Actions job completed with status: ${{ job.status }}'
      if: always() 
